### ISSUE TITLE
Add sphinx_build travis warning check  to branch issue362-client-base-smurf_control 

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#387] opened 2020-04-06 18:41 UTC
pysmurf branch issue362-client-base-smurf_control now builds without any sphinx warnings.  @jesusvasquez333 before I issue a pull request to master, could you please add the travis check you mentioned that chokes if there are any sphinx_build warnings (not just errors) to branch issue362-client-base-smurf_control?

**Comment by jesusvasquez333** [comment] 2020-04-06 20:58
Running `make html` in the `issue362-client-base-smurf_control` still shows a lot of warnings: https://travis-ci.com/github/slaclab/pysmurf/jobs/315575834

**Comment by jesusvasquez333** [comment] 2020-04-06 21:27
I ran the `make html` command manually on branch `issue362-client-base-smurf_control`, and I don't see any warnings on the client code. I only see the following warnings regarding some sections of the core code:
```
cryo@smurf-srv13:~/jesus/pysmurf/docs$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v2.2.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 20 source files that are out of date
updating environment: [new config] 20 added, 0 changed, 0 removed
reading sources... [100%] user/quickstart
WARNING: autodoc: failed to import module 'devices._PcieCard' from module 'pysmurf.core'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'devices._SmurfApplication' from module 'pysmurf.core'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'devices._UdpReceiver' from module 'pysmurf.core'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'CmbEth' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/CmbEth.py", line 24, in <module>
    from pysmurf.core.roots.Common import Common
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'CmbPcie' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/CmbPcie.py", line 24, in <module>
    from pysmurf.core.roots.Common import Common
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'Common' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'DevBoardEth' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/DevBoardEth.py", line 24, in <module>
    from pysmurf.core.roots.Common import Common
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'DevBoardPcie' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/DevBoardPcie.py", line 24, in <module>
    from pysmurf.core.roots.Common import Common
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

WARNING: autodoc: failed to import module 'EmulationRoot' from module 'pysmurf.core.roots'; the following exception was raised:
Traceback (most recent call last):
  File "/home/cryo/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/EmulationRoot.py", line 24, in <module>
    from pysmurf.core.roots.Common import Common
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/roots/Common.py", line 26, in <module>
    import pysmurf.core.devices
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/__init__.py", line 22, in <module>
    from pysmurf.core.devices._UdpReceiver import UdpReceiver
  File "/home/cryo/.local/lib/python3.6/site-packages/pysmurf/core/devices/_UdpReceiver.py", line 25, in <module>
    class KeepAlive(rogue.interfaces.stream.Master, threading.Thread):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/quickstart
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 9 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
cryo@smurf-srv13:~/jesus/pysmurf/docs$
```

**Comment by jesusvasquez333** [comment] 2020-04-06 21:28
I'm closing this issue as it is at this point a duplicate of #382

**Closed by jesusvasquez333** 2020-04-06 21:28 UTC
Labels: enhancement
